---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: image-registry-credentials
  namespace: workflows
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets-store
  target:
    name: image-registry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {{ .dockerconfig | toString }}
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: workflows-credentials
