---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry-credentials
  namespace: workflows
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: docker-registry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {{ printf "{{ .dockerconfig | toString }}" }}
        config.json: >-
          {{ printf "{{ .dockerconfig | toString }}" }}
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: workflows-credentials
        property: docker-registry-credentials
